//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 02.05.2022 19:20:35
namespace stp7Model
{
    
    /// <summary>
    /// There are no comments for stp7Entities in the schema.
    /// </summary>
    public partial class stp7Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new stp7Entities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public stp7Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Author> Author
        {
            get
            {
                if ((this._Author == null))
                {
                    this._Author = base.CreateQuery<Author>("Author");
                }
                return this._Author;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Author> _Author;
        /// <summary>
        /// There are no comments for Book in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Book> Book
        {
            get
            {
                if ((this._Book == null))
                {
                    this._Book = base.CreateQuery<Book>("Book");
                }
                return this._Book;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Book> _Book;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("sysdiagrams");
                }
                return this._sysdiagrams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAuthor(Author author)
        {
            base.AddObject("Author", author);
        }
        /// <summary>
        /// There are no comments for Book in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBook(Book book)
        {
            base.AddObject("Book", book);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"stp7Model\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Enti" +
                "tyType Name=\"Author\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"htt" +
                "p://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"name\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Property N" +
                "ame=\"book_id\" Type=\"Edm.Int32\" /><NavigationProperty Name=\"Book\" Relationship=\"s" +
                "tp7Model.FK_Author_Book\" ToRole=\"Book\" FromRole=\"Author\" /></EntityType><EntityT" +
                "ype Name=\"Book\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://s" +
                "chemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"name\" Type=\"E" +
                "dm.String\" Nullable=\"false\" MaxLength=\"70\" FixedLength=\"false\" Unicode=\"false\" /" +
                "><Property Name=\"descrition\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"fals" +
                "e\" Unicode=\"false\" /><Property Name=\"year\" Type=\"Edm.Int32\" /><NavigationPropert" +
                "y Name=\"Author\" Relationship=\"stp7Model.FK_Author_Book\" ToRole=\"Author\" FromRole" +
                "=\"Book\" /></EntityType><EntityType Name=\"sysdiagrams\"><Key><PropertyRef Name=\"di" +
                "agram_id\" /></Key><Property Name=\"name\" Type=\"Edm.String\" Nullable=\"false\" MaxLe" +
                "ngth=\"128\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"principal_id\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"diagram_id\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.mic" +
                "rosoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"version\" Type=\"Edm.Int3" +
                "2\" /><Property Name=\"definition\" Type=\"Edm.Binary\" MaxLength=\"Max\" FixedLength=\"" +
                "false\" /></EntityType><Association Name=\"FK_Author_Book\"><End Type=\"stp7Model.Bo" +
                "ok\" Role=\"Book\" Multiplicity=\"0..1\" /><End Type=\"stp7Model.Author\" Role=\"Author\"" +
                " Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Book\"><PropertyRef N" +
                "ame=\"id\" /></Principal><Dependent Role=\"Author\"><PropertyRef Name=\"book_id\" /></" +
                "Dependent></ReferentialConstraint></Association></Schema><Schema Namespace=\"Serv" +
                "er\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"" +
                "stp7Entities\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Author\" EntityT" +
                "ype=\"stp7Model.Author\" /><EntitySet Name=\"Book\" EntityType=\"stp7Model.Book\" /><E" +
                "ntitySet Name=\"sysdiagrams\" EntityType=\"stp7Model.sysdiagrams\" /><AssociationSet" +
                " Name=\"FK_Author_Book\" Association=\"stp7Model.FK_Author_Book\"><End Role=\"Author\"" +
                " EntitySet=\"Author\" /><End Role=\"Book\" EntitySet=\"Book\" /></AssociationSet></Ent" +
                "ityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for stp7Model.Author in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Author
    {
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Author CreateAuthor(int ID)
        {
            Author author = new Author();
            author.id = ID;
            return author;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property book_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> book_id
        {
            get
            {
                return this._book_id;
            }
            set
            {
                this.Onbook_idChanging(value);
                this._book_id = value;
                this.Onbook_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _book_id;
        partial void Onbook_idChanging(global::System.Nullable<int> value);
        partial void Onbook_idChanged();
        /// <summary>
        /// There are no comments for Book in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Book Book
        {
            get
            {
                return this._Book;
            }
            set
            {
                this._Book = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Book _Book;
    }
    /// <summary>
    /// There are no comments for stp7Model.Book in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Book
    {
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Book CreateBook(int ID, string name)
        {
            Book book = new Book();
            book.id = ID;
            book.name = name;
            return book;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property descrition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string descrition
        {
            get
            {
                return this._descrition;
            }
            set
            {
                this.OndescritionChanging(value);
                this._descrition = value;
                this.OndescritionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _descrition;
        partial void OndescritionChanging(string value);
        partial void OndescritionChanged();
        /// <summary>
        /// There are no comments for Property year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> year
        {
            get
            {
                return this._year;
            }
            set
            {
                this.OnyearChanging(value);
                this._year = value;
                this.OnyearChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _year;
        partial void OnyearChanging(global::System.Nullable<int> value);
        partial void OnyearChanged();
        /// <summary>
        /// There are no comments for Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Author> Author
        {
            get
            {
                return this._Author;
            }
            set
            {
                if ((value != null))
                {
                    this._Author = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Author> _Author = new global::System.Collections.ObjectModel.Collection<Author>();
    }
    /// <summary>
    /// There are no comments for stp7Model.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("diagram_id")]
    public partial class sysdiagrams
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this._principal_id = value;
                this.Onprincipal_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this._diagram_id = value;
                this.Ondiagram_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this._version = value;
                this.OnversionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] definition
        {
            get
            {
                if ((this._definition != null))
                {
                    return ((byte[])(this._definition.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OndefinitionChanging(value);
                this._definition = value;
                this.OndefinitionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
}
